name: Merge Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: oss-fuzz
      - uses: actions/cache@v4
        id: cache-repo
        with:
          path: "**/*"
          key: "key"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: wattmto/oss-fuzz
          ref: 'master'
      - name: Add Upstream
        if: steps.cache-repo.outputs.cache-hit != 'true'
        run: |
          git remote add upstream https://github.com/google/oss-fuzz
      - name: Merge Upstream
        run: |
          git pull
          git fetch upstream master
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
